# Generated by Django 4.2 on 2024-02-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_post_tags_alter_post_topics'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE content_tag DROP COLUMN IF EXISTS count;",
            reverse_sql="ALTER TABLE content_tag ADD COLUMN count integer NOT NULL DEFAULT 0;",
        ),
    ]