# Generated by Django 4.2 on 2024-02-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20240220_1342'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE content_tag DROP COLUMN IF EXISTS protected;",
            reverse_sql="ALTER TABLE content_tag ADD COLUMN protected integer NOT NULL DEFAULT 0;",
        ),
    ]