# Generated by Django 4.2 on 2024-02-23 11:55

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20240220_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='published', max_length=11),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='published', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
