# Generated by Django 4.2 on 2024-02-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_post_status_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
