# Generated by Django 4.2 on 2024-02-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_post_tags_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
