# Generated by Django 4.2 on 2024-02-24 00:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tool',
            name='status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='published', max_length=11),
        ),
        migrations.AlterField(
            model_name='tool',
            name='body',
            field=tinymce.models.HTMLField(blank=True, default='published', null=True),
        ),
    ]
