# Generated by Django 4.2 on 2024-02-26 11:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_topic_options_tool_status_alter_tool_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
