# Generated by Django 4.2 on 2024-02-26 14:33

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_tool_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='published', max_length=11)),
                ('topics', models.ManyToManyField(to='content.topic')),
            ],
        ),
    ]
