# Generated by Django 4.2 on 2024-02-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='content.topic'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='content.topic'),
        ),
    ]
