# Generated by Django 4.2 on 2024-02-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_app_topics_alter_tool_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App',
        ),
    ]
