# Generated by Django 4.2 on 2024-02-26 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_delete_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
