# Generated by Django 4.2 on 2024-03-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_tool_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
    ]
