# Generated by Django 4.2 on 2024-03-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_post_indexed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='topics',
            field=models.ManyToManyField(blank=True, to='content.topic'),
        ),
    ]
